/** Generated by scripts/generate-lifestyle-images.mjs. Do not edit manually. */
export const lifestyleItemImageSets: Record<string, readonly string[]> = {
  "Private Jets": [
    "/images/aviation/privatejet/jet-boarding.jpg",
    "/images/aviation/privatejet/jet-hangar.jpg",
    "/images/aviation/privatejet/jet-interior.jpg",
    "/images/aviation/privatejet/jet-rs-tarmac.jpg",
    "/images/aviation/privatejet/jet-side.jpg",
    "/images/aviation/privatejet/jet-sunset-front.jpg"
  ],
  "Air Ambulance": [
    "/images/aviation/airabulance/PHOTO-2026-07-12-11-27-55.jpg",
    "/images/aviation/airabulance/IMG_7811.JPG",
    "/images/aviation/airabulance/IMG_7814.JPG",
    "/images/aviation/airabulance/PHOTO-2026-07-12-11-28-34 2.jpg",
    "/images/aviation/airabulance/PHOTO-2026-07-12-11-28-34.jpg",
    "/images/aviation/airabulance/PHOTO-2026-07-12-11-28-35.jpg"
  ],
  "Helicopter Charter": [
    "/images/aviation/helicopter/PHOTO-2026-07-12-11-36-09 4.jpg",
    "/images/aviation/helicopter/PHOTO-2026-07-12-11-36-09.jpg",
    "/images/aviation/helicopter/PHOTO-2026-07-12-11-37-16.jpg"
  ],
  "VIP Airport Assistance": [
    "/images/airportassistance/ChatGPT Image Jul 22, 2026, 10_34_36 PM (1).png",
    "/images/airportassistance/ChatGPT Image Jul 22, 2026, 10_34_36 PM (2).png",
    "/images/airportassistance/ChatGPT Image Jul 22, 2026, 10_34_37 PM (3).png",
    "/images/airportassistance/ChatGPT Image Jul 22, 2026, 10_34_37 PM (4).png"
  ],
  "Yacht Charter": [
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-43-45 2.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-43-46 5.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-43-46 6.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-43-46 7.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-43-46 8.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-57-46 3.jpg",
    "/images/marine/yatchchatter/PHOTO-2026-07-12-16-57-46.jpg"
  ],
  "Superyachts": [
    "/images/marine/superyatch/PHOTO-2026-07-12-16-58-41 2.jpg",
    "/images/marine/superyatch/PHOTO-2026-07-12-16-58-41 3.jpg",
    "/images/marine/superyatch/PHOTO-2026-07-12-16-58-41 4.jpg",
    "/images/marine/superyatch/PHOTO-2026-07-12-16-58-41.jpg"
  ],
  "Jet Ski Rental": [
    "/images/marine/jetski/DSC02550.jpeg",
    "/images/marine/jetski/DSC02946.jpeg",
    "/images/marine/jetski/DSC03042.jpeg",
    "/images/marine/jetski/DSC03048.jpeg",
    "/images/marine/jetski/IMG_7311 (1).PNG",
    "/images/marine/jetski/IMG_7312 (1).PNG",
    "/images/marine/jetski/IMG_7313 (1).JPG",
    "/images/marine/jetski/IMG_7314 (1).JPG"
  ],
  "Luxury Car Rental": [
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-07 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-07.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-08 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-08.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-09 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-09 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-09 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-09 5.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-09.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-10 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-10 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-10 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-10 5.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-10.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-11 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-11 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-11 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-11.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12 5.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12 6.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-12.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-13 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-13 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-13 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-13 5.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-13.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-14 2.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-14 3.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-14 4.jpg",
    "/images/automotives/luxurycarrental/PHOTO-2026-07-12-19-17-14.jpg"
  ],
  "Supercar Rental": [
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-47.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-48 2.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-48 3.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-48.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49 2.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49 3.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49 4.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49 5.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49 6.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-49.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-50 2.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-50 3.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-50 4.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-50 5.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-50.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-51 2.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-51 3.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-51.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-52 2.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-52 3.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-52 4.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-52.jpg",
    "/images/automotives/supercarrental/PHOTO-2026-07-12-19-18-53.jpg"
  ],
  "Luxury Car Delivery": [
    "/images/automotives/luxurycar-delivery/PHOTO-2026-07-12-19-19-41.jpg"
  ],
  "Chauffeur Service": [
    "/images/automotives/chauffeurservice/IMG_7373 2.PNG",
    "/images/automotives/chauffeurservice/IMG_7373.PNG",
    "/images/automotives/chauffeurservice/IMG_7384 2.PNG",
    "/images/automotives/chauffeurservice/IMG_7384.PNG",
    "/images/automotives/chauffeurservice/IMG_7389 2.PNG",
    "/images/automotives/chauffeurservice/IMG_7389.PNG",
    "/images/automotives/chauffeurservice/IMG_7391 2.PNG",
    "/images/automotives/chauffeurservice/IMG_7391.PNG",
    "/images/automotives/chauffeurservice/IMG_7395 2.PNG",
    "/images/automotives/chauffeurservice/PHOTO-2026-07-12-19-20-06 2.jpg"
  ],
  "Security Chauffeur": [
    "/images/automotives/security-chauffeur/PHOTO-2026-07-12-19-20-06 2.jpg",
    "/images/automotives/security-chauffeur/PHOTO-2026-07-12-19-23-34.jpg",
    "/images/automotives/security-chauffeur/PHOTO-2026-07-12-19-28-05.jpg"
  ],
  "Luxury Villas": [
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-21 2.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-21.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-22 2.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-22 3.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-22 4.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-22 5.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-22.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-23 2.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-23 3.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-23 4.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-23 5.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-23.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-24 2.jpg",
    "/images/luxury-villa/PHOTO-2026-07-12-19-37-24.jpg",
    "/images/luxury-villa/villa-modern.jpg"
  ],
  "Luxury Apartments": [
    "/images/luxury-apartment/PHOTO-2026-07-12-19-38-14.jpg",
    "/images/luxury-apartment/PHOTO-2026-07-12-19-38-15 2.jpg",
    "/images/luxury-apartment/PHOTO-2026-07-12-19-38-15 3.jpg",
    "/images/luxury-apartment/PHOTO-2026-07-12-19-38-15 4.jpg",
    "/images/luxury-apartment/PHOTO-2026-07-12-19-38-15.jpg"
  ],
  "Hotels & Resorts": [
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-05 2.jpg",
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-05 3.jpg",
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-05 4.jpg",
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-05.jpg",
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-06 2.jpg",
    "/images/hotel-reservations /PHOTO-2026-07-12-20-59-06.jpg"
  ],
  "Restaurant Reservations": [
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-06 2.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-06.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-07 2.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-07 3.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-07.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-08 2.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-08.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-09 2.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-09 3.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-42-09.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-52-28 2.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-52-28 3.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-21-52-28.jpg",
    "/images/restaurant-reservation/PHOTO-2026-07-12-23-03-58 2.jpg"
  ],
  "Beach Clubs": [
    "/images/beachclub/IMG_7362.PNG",
    "/images/beachclub/IMG_7363.PNG",
    "/images/beachclub/IMG_7366.PNG",
    "/images/beachclub/IMG_7367.PNG",
    "/images/beachclub/IMG_7368.PNG",
    "/images/beachclub/IMG_7369.PNG",
    "/images/beachclub/IMG_7370.PNG",
    "/images/beachclub/IMG_7371.PNG",
    "/images/beachclub/JPEG image-443A-B186-CF-5.jpeg"
  ],
  "Nightlife": [
    "/images/night-life/PHOTO-2026-07-12-21-52-28 2.jpg",
    "/images/night-life/PHOTO-2026-07-12-21-52-28 3.jpg",
    "/images/night-life/PHOTO-2026-07-12-21-52-28.jpg",
    "/images/night-life/PHOTO-2026-07-12-21-52-29.jpg"
  ],
  "VIP Events": [
    "/images/vip-event/PHOTO-2026-07-12-22-22-17 2.jpg",
    "/images/vip-event/PHOTO-2026-07-12-22-22-17.jpg",
    "/images/vip-event/PHOTO-2026-07-12-22-22-18 2.jpg",
    "/images/vip-event/PHOTO-2026-07-12-22-22-18 3.jpg",
    "/images/vip-event/PHOTO-2026-07-12-22-22-18.jpg"
  ],
  "Desert Safari": [
    "/images/desertsafari/IMG_7319 (1).PNG",
    "/images/desertsafari/IMG_7322 (1).PNG",
    "/images/desertsafari/IMG_7324 (1).JPG",
    "/images/desertsafari/IMG_7325 (1).JPG",
    "/images/desertsafari/IMG_7326 (1).JPG",
    "/images/desertsafari/IMG_7328 (1).JPG",
    "/images/desertsafari/IMG_7329 (1).JPG",
    "/images/desertsafari/IMG_7330 (1).JPG",
    "/images/desertsafari/IMG_7331 (1).JPG"
  ],
  "Yacht Parties": [
    "/images/yatch-parties/PHOTO-2026-07-12-23-03-58 2.jpg",
    "/images/yatch-parties/PHOTO-2026-07-12-23-03-58 3.jpg",
    "/images/yatch-parties/PHOTO-2026-07-12-23-03-58.jpg"
  ],
  "Skydiving": [
    "/images/skydiving/PHOTO-2026-07-12-23-32-42 2.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-42 3.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-42.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-43 2.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-43 3.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-43 4.jpg",
    "/images/skydiving/PHOTO-2026-07-12-23-32-43.jpg"
  ],
  "Fishing Charters": [
    "/images/fishing-charters/PHOTO-2026-07-12-23-45-36 2.jpg",
    "/images/fishing-charters/PHOTO-2026-07-12-23-45-36 3.jpg",
    "/images/fishing-charters/PHOTO-2026-07-12-23-45-36 4.jpg",
    "/images/fishing-charters/PHOTO-2026-07-12-23-45-36 5.jpg",
    "/images/fishing-charters/PHOTO-2026-07-12-23-45-36.jpg"
  ],
  "Car Track Days": [
    "/images/car-track-days/PHOTO-2026-07-13-07-46-57 2.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-57 3.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-57.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-58 2.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-58 3.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-58.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-59 2.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-59 3.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-59 4.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-46-59.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-47-00 2.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-47-00 3.jpg",
    "/images/car-track-days/PHOTO-2026-07-13-07-47-00.jpg"
  ],
  "Car Drift": [
    "/images/car-drift/PHOTO-2026-07-13-09-00-15 2.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-15 3.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-15 4.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-15 5.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-15.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-16 2.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-16 3.jpg",
    "/images/car-drift/PHOTO-2026-07-13-09-00-16.jpg"
  ],
  "Karting": [
    "/images/karting/PHOTO-2026-07-13-10-42-22.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-23 2.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-23 3.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-23 4.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-23 5.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-23.jpg",
    "/images/karting/PHOTO-2026-07-13-10-42-24.jpg"
  ],
  "Golf": [
    "/images/golf/PHOTO-2026-07-14-10-24-43.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-44 2.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-44 3.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-44 4.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-44 5.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-44.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-45 2.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-45 3.jpg",
    "/images/golf/PHOTO-2026-07-14-10-24-45.jpg"
  ],
  "Horse Riding": [
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20 2.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20 3.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20 4.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20 5.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20 6.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-20.jpg",
    "/images/horse-riding/PHOTO-2026-07-14-20-36-21.jpg"
  ],
  "Shooting Range": [
    "/images/shooting/PHOTO-2026-07-15-00-53-42.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43 2.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43 3.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43 4.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43 5.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43 6.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-43.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-44 2.jpg",
    "/images/shooting/PHOTO-2026-07-15-00-53-44.jpg"
  ],
  "Private Chef": [
    "/images/chef/PHOTO-2026-07-18-15-00-01 2.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-01 3.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-01.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-02 2.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-02 3.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-02 4.jpg",
    "/images/chef/PHOTO-2026-07-18-15-00-02.jpg"
  ],
  "Spa & Wellness": [
    "/images/spa/PHOTO-2026-07-18-14-22-38 3.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-38.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-39 2.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-39 3.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-39 4.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-39 5.jpg",
    "/images/spa/PHOTO-2026-07-18-14-22-39.jpg"
  ],
  "Personal Trainer": [
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-36.jpg",
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-39.jpg",
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-40 2.jpg",
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-40.jpg",
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-41 2.jpg",
    "/images/personaltrainer/PHOTO-2026-07-19-17-38-41.jpg"
  ],
  "Close Protection": [
    "/images/closeprotection/PHOTO-2026-07-19-17-53-55 2.jpg",
    "/images/closeprotection/PHOTO-2026-07-19-17-53-55 3.jpg",
    "/images/closeprotection/PHOTO-2026-07-19-17-53-55 4.jpg",
    "/images/closeprotection/PHOTO-2026-07-19-17-53-55.jpg",
    "/images/closeprotection/PHOTO-2026-07-19-17-53-56.jpg"
  ],
  "Event Security": [
    "/images/lifestyle-concierge/items/event-security.png"
  ]
}
